repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: ruff
        require_serial: true
        types: [python]